manp:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  world_to_base_state_contoller:
    type: effort_controllers/JointEffortController
    joint: world_to_base
    pid: {p: 1.0, i: 0.0, d: 0.0}
  link1_to_link2_state_controller:
    type: effort_controllers/JointEffortController
    joint: link1_to_link2
    pid: {p: 1.0, i: 0., d: 0.0}
  link2_to_link3_state_controller:
    type: effort_controllers/JointEffortController
    joint: link2_to_link3
    pid: {p: 1.0, i: 0.0, d: 0.0}
