<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manp">

<!-- Constants -->
	
	<xacro:property name="pi" value="3.14159265359"/>
	<xacro:property name="width" value="0.5"/>
	<xacro:property name="height" value="4"/>
	<xacro:property name="base_h" value="0.5"/>
	<xacro:property name="base_r" value="1"/>
	<xacro:property name="base_link_mass" value="1"/>
	<xacro:property name="link_mass" value="1"/>

<!-- Links -->

	<link name="world"/>

	<link name="base_link">
		<visual>
			<geometry>
				<cylinder length="${base_h}" radius="${base_r}"/>
			</geometry>
			<origin xyz="0 0 ${base_h/2}"/>
		</visual>
		<inertial>
      			<mass value="${base_link_mass}"/>
      			<inertia 
				ixx="${base_link_mass*(3*base_r*base_r+base_h*base_h)/12}" ixy="0.0" ixz="0.0" 
				iyy="${base_link_mass*(3*base_r*base_r+base_h*base_h)/12}" iyz="0.0" izz="${base_link_mass*base_r*base_r/2}"
			/>
    		</inertial>
	</link>

	<link name="link1">
		<visual>
			<geometry>
				<box size="${width} ${width} ${height/2}"/>
			</geometry>
			<origin xyz="0 0 ${height/4}"/>
		</visual>
		<inertial>
      			<mass value="${link_mass/2}"/>
      			<inertia ixx="${link_mass*height*height/6}" ixy="0.0" ixz="0.0" iyy="${link_mass*height*height/6}" iyz="0.0" izz="1e-10"/>
    		</inertial>
	</link>

	<link name="link2">
		<visual>
			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
			<origin xyz="0 0 ${height/2}"/>
		</visual>
		<inertial>
      			<mass value="${link_mass}"/>
      			<inertia ixx="${link_mass*height*height/3}" ixy="0.0" ixz="0.0" iyy="${link_mass*height*height/3}" iyz="0.0" izz="1e-10"/>
    		</inertial>
	</link>

	<link name="link3">
		<visual>
			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
			<origin xyz="0 0 ${height/2}"/>
		</visual>
		<inertial>
      			<mass value="${link_mass}"/>
      			<inertia ixx="${link_mass*height*height/3}" ixy="0.0" ixz="0.0" iyy="${link_mass*height*height/3}" iyz="0.0" izz="1e-10"/>
    		</inertial>
	</link>

<!-- ########### -->

<!-- Joints -->
	
	<joint name="world_to_base" type="continuous">
		<parent link="world"/>
		<child link="base_link"/>
		<origin xyz="0 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>
	
	<joint name="base_to_link1" type="fixed">
		<parent link="base_link"/>
		<child link="link1"/>
		<origin xyz="0 0 ${base_h}"/>
		<axis xyz="0 1 0"/>
	</joint>

	<joint name="link1_to_link2" type="continuous">
		<parent link="link1"/>
		<child link="link2"/>
		<origin xyz="0 ${-width} ${height/2-0.5}"/>
		<axis xyz="0 1 0"/>
	</joint>
	
	<joint name="link2_to_link3" type="continuous">
		<parent link="link2"/>
		<child link="link3"/>
		<origin xyz="0 ${width} ${height-0.5}"/>
		<axis xyz="0 1 0"/>
	</joint>

<!-- ###### -->

</robot>
