<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manp">

<!-- Constants -->
	
	<xacro:property name="pi" value="3.14159265359"/>
	<xacro:property name="width" value="0.5"/>
	<xacro:property name="height" value="4"/>
	<xacro:property name="base_h" value="0.5"/>
	<xacro:property name="base_r" value="1"/>
	<xacro:property name="base_link_mass" value="20"/>
	<xacro:property name="link_mass" value="40"/>

<!-- Links -->

	<link name="world"/>

	<link name="base_link">
		<visual>
			<geometry>
				<cylinder length="${base_h}" radius="${base_r}"/>
			</geometry>
			<origin xyz="0 0 ${base_h/2}"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${base_h/2}"/>
      			<mass value="${base_link_mass}"/>
      			<inertia 
				ixx="${base_link_mass*(3*base_r*base_r+base_h*base_h)/12}" ixy="1e-3" ixz="1e-3" 
				iyy="${base_link_mass*(3*base_r*base_r+base_h*base_h)/12}" iyz="1e-3" izz="${base_link_mass*base_r*base_r/2}"
			/>
    		</inertial>
		<collision>
      			<geometry>
        			<cylinder length="${base_h}" radius="${base_r}"/>
      			</geometry>
      			<origin xyz="0 0 ${base_h/2}"/>
    		</collision>
	</link>

	<link name="link1">
		<visual>
			<geometry>
				<box size="${width} ${width} ${height/2}"/>
			</geometry>
			<origin xyz="0 0 ${height/4}"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height/4}"/>
      			<mass value="${link_mass/2}"/>
      			<inertia ixx="${link_mass*height*height/6}" ixy="1e-3" ixz="1e-3" iyy="${link_mass*height*height/6}" iyz="1e-3" izz="1e-3"/>
    		</inertial>
		<collision>
      			<geometry>
				<box size="${width} ${width} ${height/2}"/>
			</geometry>
			<origin xyz="0 0 ${height/4}"/>
    		</collision>
	</link>

	<link name="link2">
		<visual>
			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
			<origin xyz="0 0 ${height/2}"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height/2}"/>
      			<mass value="${link_mass}"/>
      			<inertia ixx="${link_mass*height*height/3}" ixy="1e-3" ixz="1e-3" iyy="${link_mass*height*height/3}" iyz="1e-3" izz="1e-3"/>
    		</inertial>
		<collision>
      			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
			<origin xyz="0 0 ${height/2}"/>
    		</collision>
	</link>

	<link name="link3">
		<visual>
			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
			<origin xyz="0 0 ${height/2}"/>
		</visual>
		<inertial>
			<origin xyz="0 0 ${height/2}"/>
      			<mass value="${link_mass}"/>
      			<inertia ixx="${link_mass*height*height/3}" ixy="1e-3" ixz="1e-3" iyy="${link_mass*height*height/3}" iyz="1e-3" izz="1e-3"/>
    		</inertial>
		<collision>
			<geometry>
				<box size="${width} ${width} ${height}"/>
			</geometry>
			<origin xyz="0 0 ${height/2}"/>
		</collision>
	</link>

<!-- ########### -->

<!-- Joints -->
	
	<joint name="world_to_base" type="continuous">
		<parent link="world"/>
		<child link="base_link"/>
		<origin xyz="0 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>
	
	<joint name="base_to_link1" type="fixed">
		<parent link="base_link"/>
		<child link="link1"/>
		<origin xyz="0 0 ${base_h}"/>
	</joint>

	<joint name="link1_to_link2" type="continuous">
		<parent link="link1"/>
		<child link="link2"/>
		<origin xyz="0 ${-width-0.1} ${height/2-0.5}" rpy="0 0 0"/>
		<axis xyz="0 1 0"/>
	</joint>
	
	<joint name="link2_to_link3" type="continuous">
		<parent link="link2"/>
		<child link="link3"/>
		<origin xyz="0 ${width+0.1} ${height-0.5}"/>
		<axis xyz="0 1 0"/>
	</joint>

<!-- ###### -->

<!-- Transmissions -->

	<transmission name="world_to_base">
		<type>transmission_interface/SimpleTransmission</type>
    		<joint name="world_to_base">
      			<hardwareInterface>EffortJointInterface</hardwareInterface>
    		</joint>
    		<actuator name="z-motor">
      			<mechanicalReduction>1</mechanicalReduction>
      			<hardwareInterface>EffortJointInterface</hardwareInterface>
    		</actuator>
  	</transmission>

	<transmission name="link1_to_link2">
		<type>transmission_interface/SimpleTransmission</type>
    		<joint name="link1_to_link2">
      			<hardwareInterface>EffortJointInterface</hardwareInterface>
    		</joint>
    		<actuator name="y-motor2">
      			<mechanicalReduction>1</mechanicalReduction>
      			<hardwareInterface>EffortJointInterface</hardwareInterface>
    		</actuator>
  	</transmission>
	
	<transmission name="link2_to_link3">
		<type>transmission_interface/SimpleTransmission</type>
    		<joint name="link2_to_link3">
      			<hardwareInterface>EffortJointInterface</hardwareInterface>
    		</joint>
    		<actuator name="y-motor3">
      			<mechanicalReduction>1</mechanicalReduction>
      			<hardwareInterface>EffortJointInterface</hardwareInterface>
    		</actuator>
  	</transmission>

<!-- ############# -->

<!-- Setting self collide for every link -->

	<gazebo reference="base_link">
    		<selfCollide>true</selfCollide>
	</gazebo>

	<gazebo reference="link1">
    		<selfCollide>true</selfCollide>
	</gazebo>
	
	<gazebo reference="link2">
    		<selfCollide>true</selfCollide>
	</gazebo>

	<gazebo reference="link3">
    		<selfCollide>true</selfCollide>
	</gazebo>

<!-- ################################# -->

	<gazebo>
    		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      			<robotNamespace>/manp</robotNamespace>
    		</plugin>
	</gazebo>
</robot>
